// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWt1IY9IrfMfkhxSZ2bF4UM6rvl_luWE',
    appId: '1:315447478704:web:03c84a66e1b1ceaa59ae75',
    messagingSenderId: '315447478704',
    projectId: 'flyz-58f1b',
    authDomain: 'flyz-58f1b.firebaseapp.com',
    storageBucket: 'flyz-58f1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeCgeEAwGug4UdhVwfowKrFuQAsv59upI',
    appId: '1:315447478704:android:f90af8e088e3f35b59ae75',
    messagingSenderId: '315447478704',
    projectId: 'flyz-58f1b',
    storageBucket: 'flyz-58f1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADSRpuLvuv-p82PMfivjCDrelq_l4c6p0',
    appId: '1:315447478704:ios:efcd5b8860d980bc59ae75',
    messagingSenderId: '315447478704',
    projectId: 'flyz-58f1b',
    storageBucket: 'flyz-58f1b.firebasestorage.app',
    iosBundleId: 'com.flyz.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADSRpuLvuv-p82PMfivjCDrelq_l4c6p0',
    appId: '1:315447478704:ios:adf1e798237ff5fa59ae75',
    messagingSenderId: '315447478704',
    projectId: 'flyz-58f1b',
    storageBucket: 'flyz-58f1b.firebasestorage.app',
    iosBundleId: 'com.flyz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAWt1IY9IrfMfkhxSZ2bF4UM6rvl_luWE',
    appId: '1:315447478704:web:a571caa7990a81b959ae75',
    messagingSenderId: '315447478704',
    projectId: 'flyz-58f1b',
    authDomain: 'flyz-58f1b.firebaseapp.com',
    storageBucket: 'flyz-58f1b.firebasestorage.app',
  );
}
